### ISSUE TITLE
Removing cobra and toml

### ISSUE THREAD

**Issue by atakanyenel** [RadhiFadlillah/duit#1]
Hey, that's a great project. I pulled it and playing with it. 

I see that you are using cobra package. To me, this project is a server application and not a CLI application, so cobra seems like an overkill to read 2 arguments and display a help message. I replaced it with the flag package and removed cobra from dependencies.

You are also using toml for reading configuration data. Your data is fairly simple , so I replaced toml with yaml and removed the toml dependency. Yaml still adds a dependency to go.mod, but it's an official one, so less maintenance. 

Those changes really does not affect features at all but Go is famous for it's standart library, so it seemed liked a good idea.

What do you think ?

**Comment by RadhiFadlillah** [comment]
Hi @atakanyenel, thanks for the suggestion.

---

I use `cobra` package in favor of the `flag` package from standard library is because:

1. The `flag` package doesn't support shorthand parameter. For example, thanks to `cobra`, we can run `duit` like this :

   ```
   duit -p 9000
   ```

   or for people who prefer verbose command, like this :

   ```
   duit --port 9000
   ```

   As far as I know, there is no easy way to do this using `flag` package.

2. By using `cobra`, we get a neat command documentation like this :

   ```
   $ duit -h

   Duit, the simple money manager

   Usage:
     duit [flags]
   
   Flags:
     -c, --config string   path to config file (default "/home/radhi/.config/duit/config.toml")
     -h, --help            help for duit
     -p, --port int        port used by the server (default 8080)
   ```

   For comparison, here is how it would look like if we are using `flag` package :

   ```
   $ duit -h

   Usage of duit:
     -config string
           path to config file (default "/home/radhi/.config/duit/config.toml")
     -port int
           port used by the server (default 8080)
   ```

   It might be just my personal opinion, but I think the one that generated by `cobra` is far more tidier than the one from `flag` package.

3. I've tested it and the size of output binary is not too different between using `cobra` and `flag` package, with former a few kilobytes bigger than latter.

---

For the configuration I prefer TOML than YAML, mostly because aesthetic issue. Consider following YAML file :

```yaml
title: YAML Example

database:
  server: 192.168.1.1
  connection_max: 5000
```

Compare it with TOML file :

```toml
title = "TOML Example"
 
[database]
server = "192.168.1.1"
connection_max = 5000
```

I like how TOML requires quotes around string to differentiate it with numeric value. I also like how it doesn't really need the indentation to parse. That's why I ended up using TOML.

---

Besides points that I've mentioned above, I don't think we need to change the code and configuration format, especially since they work fine without issues right now. Like common saying: "Don't fix what's not broken".
